services:
  api:
    build: .
    ports:
      - "5000:5000"
    volumes:
      # Mount the model directory to avoid rebuilding the image for model changes
      - ./model:/usr/src/app/model

  prometheus:
    image: prom/prometheus:v2.45.0
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--web.external-url=http://your_domain.com/prometheus"

  grafana:
    image: grafana/grafana:9.5.3
    ports:
      - "3100:3000"
    user: "$(id -u)"
    volumes:
      - ./monitoring/grafana:/var/lib/grafana
    environment:
      - GF_SERVER_ROOT_URL=http://your_domain.com/grafana
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
